# Source file: https://github.com/Elttob/Fusion/blob/main/mkdocs.yml

site_name: pyrbx
site_url: https://github.com/anyastrophic/pyrbx
repo_name: anyastrophic/pyrbx
repo_url: https://github.com/anyastrophic/pyrbx
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - content.code.annotate

extra_css:
  - assets/theme.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - roblox
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_if_no_docstring: yes
            show_signature_annotations: yes
            show_root_heading: yes

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anyastrophic/pyrbx
      name: pyrbx on GitHub
  version:
    provider: mike
